### PR TITLE
change the Eulerian classes out of the master and edit the cmakelist to make the Eulerian cases run in the ctest.

### PR DESCRIPTION
**Pull request by ZhentongWang**
change the regression files further to make the tests successful in CI/MacOS

### CODE REVIEW

**Comment by ZhentongWang** [comment]
also add Yongchuan as a collaborator to review the pull request

**Comment by Xiangyu-Hu** [comment]
What did you changed for McOS?

**Comment by ZhentongWang** [comment]
> What did you changed for McOS?

At the beginning, fails in macOS show that case of flow around cylinder is unsuccessful because of regression files, so I change the regression file in the Eulerian flow around cylinder case, specifically I decrease the value in the "generateDatabase" class to generate new regression files and then use these to replace the original regression files and now Eulerian flow around cylinder case could run successfully.

**Comment by Xiangyu-Hu** [comment]
I think Zhengtong means that he decreased threshold for all systems.

**Comment by Xiangyu-Hu** [comment]
> when we generate the regression files, we would use function .generateDataBase(**5.0e-3**) in class named RegressionTestDynamicTimeWarping. At the first, in the Eulerian flow around cylinder case, I set value as **5.0e-3** to generate the regression files but failed in CI/macOS, then I decrease the value from **5.0e-3** to **1.0e-3** to generate the regression files, and then results could pass in the CI/macOS.

This is OK.

**Review by Xiangyu-Hu — APPROVED** [review]

**Pull request merged**
