### PR TITLE
Shell analytical verification w/ parameter study

### PR DESCRIPTION
**Pull request by BenceVirtonomy**
### Observations/Issues
- roof case < 10% error
- circular plate < 5% error
- half sphere is stable with hourglass, otherwise out-of-plane displacements at static state
- TODO: stress verification once the shell damping is finalized

### TEST CASE 1. - test_3d_roof_analytical
**Test case from ANSYSWorkbenchVerificationManual: VMMECH069: Barrel Vault Roof Under Self Weight**
- full shell geometry is used, not only one quarter
- shell particles are generated with uniform distribution from direct generator with dp = 1m (shell_50mm_80d_100cm.txt)

**Ansys manual:**

**Displacement, vonMises strain**

**Refinement study**
Displacement convergence per simulation: dp = 4, 2, 1 x thickness:

Displacement:

### TEST CASE 2. - test_3d_bending_circular_plate
**Test case from ANSYSWorkbenchVerificationManual: VMMECH051: Bending of a Circular Plate Using Axisymmetric Elements**
- Case 1. is built, with a pressure application
- <5% error in deflection to target

**Ansys manual:**

**Displacement, vonMises strain**

**Refinement study**
Displacement convergence per simulation: dp = 4, 2, 1 x thickness:

Displacement:

### TEST CASE 3. - test_3d_shell_stability_large_deformation
**Made-up test case to test the stability of large deformation - e.g. the simulation should not break**
- Half a sphere with the rim fixed and self-weight applied in horizontal direction

**E = 5e7 - Displacement, vonMises strain**

### CODE REVIEW

**Comment by BenceVirtonomy** [comment]
@Xiangyu-Hu @DongWuTUM stability test also included

**Comment by BenceVirtonomy** [comment]
@DongWuTUM  @Xiangyu-Hu the lattice roof case also converges for me. The CVT one is only okay with dp=4, it blows up from dp=2 on. You can test the new formulations with that.

**Comment by BenceVirtonomy** [comment]
@DongWuTUM @Xiangyu-Hu Please review, the parameter studies are updated, and the accuracy seems reasonable. The stability case also works with the current hourglass correction.

**Comment by Xiangyu-Hu** [comment]
How long do these cases take to run on the github runner ?

**Comment by BenceVirtonomy** [comment]
> How long do these cases take to run on the github runner ?

70/80 Test #70: roof_under_self_weight.dp_4 .................................   Passed  137.02 sec
73/80 Test #73: test_3d_roof_parametric_cvt .................................   Passed  137.21 sec
76/80 Test #76: sphere_compression.half_sphere ..............................   Passed  1120.80 sec

I will reduce the resolution on the half_sphere. In general, I'm only running them with the coarsest resolution, not the parameter study, those are still there but disabled for CI.

**Comment by Xiangyu-Hu** [comment]
> > How long do these cases take to run on the github runner ?
> 
> 70/80 Test #70: roof_under_self_weight.dp_4 ................................. Passed 137.02 sec 73/80 Test #73: test_3d_roof_parametric_cvt ................................. Passed 137.21 sec 76/80 Test #76: sphere_compression.half_sphere .............................. Passed 1120.80 sec
> 
> I will reduce the resolution on the half_sphere. In general, I'm only running them with the coarsest resolution, not the parameter study, those are still there but disabled for CI.

Yes. The first two are Ok. The third case takes too long time. We need decrease the resolution so that the time is less than 200 seconds.

**Comment by DongWuTUM** [comment]
@BenceVirtonomy That's great! Thank you. Yes, the third case takes too long to be a test case of SPHinXsys.

**Comment by BenceVirtonomy** [comment]
Okay, third case is reduced to half resolution and time @Xiangyu-Hu @DongWuTUM :

76/80 Test #76: sphere_compression.half_sphere ..............................   Passed  169.87 sec

**Review by Xiangyu-Hu — APPROVED** [review]

**Pull request merged**
