### PR TITLE
add boundary condition & examples

### PR DESCRIPTION
**Pull request by alundilong**
add examples:
#2D T shape in arbitrary direction
#3D T shape
#3D pipe with narrowness

### CODE REVIEW

**Comment by Xiangyu-Hu** [comment]
The test is failed due to long run time?

**Comment by SchrodingersAlphaGo** [comment]
fix

**Comment by Xiangyu-Hu** [comment]
I think that the code should be able to pass ctest on the local machine before CI in Github.

**Comment by Xiangyu-Hu** [comment]
Is the failed case can pass in your local machine?

**Comment by SchrodingersAlphaGo** [comment]
> Is the failed case can pass in your local machine?

Yes, the failed case passed ctest on the local mechine.

**Comment by Xiangyu-Hu** [comment]
OK. So you can switch off the regression case in 3d_dambreak case. then we have another try.

**Review by Xiangyu-Hu — APPROVED** [review]

**Pull request merged**
