### PR TITLE
Shell test for singularity in shell model

### PR DESCRIPTION
**Pull request by DongWuTUM**

### CODE REVIEW

**Comment by Xiangyu-Hu** [comment]
@DongWuTUM we probably update this draft pull request to shown at least 2D is working.

**Comment by DongWuTUM** [comment]
@SchrodingersAlphaGo @BenceVirtonomy @FabienPean-Virtonomy @Xiangyu-Hu 
* We finally found out and solved the singularity problem in the shell model after a series of efforts. I will continue to conduct some tests to further check the accuracy, stability, and so on. The related code will be available soon.

https://github.com/Xiangyu-Hu/SPHinXsys/assets/100197018/b93fb80d-074b-46fc-8949-1ff80a7fdf41

**Comment by Xiangyu-Hu** [comment]
Great!

**Comment by BenceVirtonomy** [comment]
Very cool!

**Comment by BenceVirtonomy** [comment]
Awesome:) It's from our CVT particle generator.

**Comment by DongWuTUM** [comment]
> Awesome:) It's from our CVT particle generator.

Will it be open source?

**Comment by Xiangyu-Hu** [comment]
What is that 3rd party lib? Actually we are considering add OCCT already for more generalized geometric modeling.

**Comment by DongWuTUM** [comment]
@SchrodingersAlphaGo @BenceVirtonomy @FabienPean-Virtonomy @Xiangyu-Hu 
### I found a problem in the shell dynamic case. 
- This problem only occurs at **high resolution**. I only tested it at low resolution before and it was fine. With high resolution, the plate appears to show **high frequency oscillations**.
- The results by the original code show the same high frequency oscillations. In other words, it's not caused by the bug fix of this time. 

### 2D plate with low resoluton:

https://github.com/Xiangyu-Hu/SPHinXsys/assets/100197018/e144c2a9-a5a7-47b1-84ec-9d1fc63c49a2

### 2D plate with high resoluton:

https://github.com/Xiangyu-Hu/SPHinXsys/assets/100197018/1f026a92-b663-4092-b306-44b8f616bee0

### 3D plate with high resoluton:

https://github.com/Xiangyu-Hu/SPHinXsys/assets/100197018/a2519a4e-5d20-4214-a176-586604b5e557

**Comment by Xiangyu-Hu** [comment]
@DongWuTUM you need pull the master so that the conflict will disappear.

**Comment by BenceVirtonomy** [comment]
> OCCT

Geogram. Please discuss with Fabien before deciding on adding major dependencies, he has a lot of experience here. @FabienPean-Virtonomy

**Comment by DongWuTUM** [comment]
### Updates:
* Fixed bugs: 
1. Integrate Cauchy stress along thickness now. Otherwise, the error of calculation results is large when large deformation;
2. Correct conversion from *dpseudo_n_d2t_* to *dangular_vel_dt_* for avoiding 90 degree singularity;
3. Correct scaling of numerical damping to solve the incorrect high frequency vibration of dynamic shell cases. 
* Optimizations: 
1. Simplify the calculation of *dpseudo_n_dt_*;
2. A dynamic shell case, named **test_3d_dynamic_plate**, is added;
3. A shell test with rigid rotation, named **test_thin_structure_dynamics**, is added in the unit tests;
4. Two test cases, **test_2d_shell** and **test_3d_arch**, are applied very large deformation; 
5. Output the von Mises stress of shell mid-surface.

**Review by Xiangyu-Hu — APPROVED** [review]

**Comment by FabienPean-Virtonomy** [comment]
OCCT is a huge beast, if you need only a small part of it, I would prefer you find a smaller alternative. Besides, it is LGPL, so it must necessarily be built as a shared library to not propagate its license to consumers of the lib. In any case, it must be an optional dependency.

**Pull request merged**
