### PR TITLE
Merge upstream/pr 2022.02.16

### PR DESCRIPTION
**Pull request by FabienPean-Virtonomy**
This PR attempts to reconcile the two repositories. We will work on the sync process on our side to avoid a difficult merge of this scale in the future. This should lead to less headache and file conflicts for everyone during merging.

Files with specific need for review
* [in_output.h](https://github.com/Xiangyu-Hu/SPHinXsys/compare/master...BenceVirtonomy:merge_upstream/PR_2022.02.16#diff-4f3cb9b96ad37e00398725e68dd75f8b924e240b3b1b21526261826ac39b534c)
* [in_output.cpp](https://github.com/Xiangyu-Hu/SPHinXsys/compare/master...BenceVirtonomy:merge_upstream/PR_2022.02.16#diff-116def3b0e2a41c0a70d501aa889702e096bbb157d3fc336cc4d154efc105879)
* [elastic_solid.cpp](https://github.com/Xiangyu-Hu/SPHinXsys/compare/master...BenceVirtonomy:merge_upstream/PR_2022.02.16#diff-531ffe9ea5d26e3436b68f074d23b748638adcb19d31c965fa693321c9f82576)
* [elastic_solid.h](https://github.com/Xiangyu-Hu/SPHinXsys/compare/master...BenceVirtonomy:merge_upstream/PR_2022.02.16#diff-8a548bb71ba67207ed10c97e4931ad884fec3a881fdb43f6a1075532a9ee934f)
* [contact_dynamics.cpp](https://github.com/Xiangyu-Hu/SPHinXsys/compare/master...BenceVirtonomy:merge_upstream/PR_2022.02.16#diff-a3de9b3ddabed276b4327f9e150397f1c3b82a4173abc173d041529157b7d724)
* [contact_dynamics.h](https://github.com/Xiangyu-Hu/SPHinXsys/compare/master...BenceVirtonomy:merge_upstream/PR_2022.02.16#diff-4de3a1f3435f4f213e3f8791e7d57364688668441180a8aac7b729a3f52f4b8f)

Tests removed from ctest due to issues with CI
* test_2d_self_contact
* test_2d_sliding
* test_2d_dambreak
* test_3d_taylor_bar

@BenceVirtonomy, if you have anything to add here

### CODE REVIEW

**Comment by BenceVirtonomy** [comment]
@Xiangyu-Hu please review our changes. We would like to merge so our repos can be aligned before other merges happen. Thank you!

**Comment by FabienPean-Virtonomy** [comment]
Restore tests as discussed earlier. Please @Xiangyu-Hu approve my account for running workflows:
```
1 workflow awaiting approval
First-time contributors need a maintainer to approve running workflows. [Learn more.](https://docs.github.com/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)
```

**Review by Xiangyu-Hu — COMMENTED** [review]
Please make sure that the new functions and classes have corresponding tests so that they can be tested after changes from other sources.

**Comment by BenceVirtonomy** [comment]
> Please make sure that the new functions and classes have corresponding tests so that they can be tested after changes from other sources.

@Xiangyu-Hu are you missing tests from our side? If yes, please specify for what. Can you please give Fabien access to run workflows?

**Pull request closed without merging**
