### PR TITLE
add  getRotationFromPseudoNormalForSmallDeformation.

### PR DESCRIPTION
**Pull request by rukawaaaaaaa**
add a new getRotationFromPseudoNormalForSmallDeformation

### CODE REVIEW

**Comment by Xiangyu-Hu** [comment]
@rukawaaaaaaa I think that CI is not able to pass.

**Comment by rukawaaaaaaa** [comment]
> @rukawaaaaaaa I think that CI is not able to pass.

It is a bit wired that the error messege shows CI is cancelled, should I try it again?

**Comment by rukawaaaaaaa** [comment]
> Thank you! Since the code should be able to work under both formulations (small and large rotations, 2D and 3D), I will modify the code.

That will be great. Now the code can not run under both formulations.  The angular accleration is in the local current configuration by using the small deformation formulation while that is in local initial configuration  by using the large deformation formulation,.

**Comment by rukawaaaaaaa** [comment]
> > Thank you! Since the code should be able to work under both formulations (small and large rotations, 2D and 3D), I will modify the code.
> 
> @DongWuTUM That will be great. Now the code can not run under both formulations. The angular accleration is in the local current configuration by using the small deformation formulation while that is in local initial configuration by using the large deformation formulation,.

**Comment by Xiangyu-Hu** [comment]
@rukawaaaaaaa @DongWuTUM I stop the CI as it can not pass before revision.

**Comment by DongWuTUM** [comment]
@rukawaaaaaaa Please look at the new pull request I created. That you proposed is actually another formulation of shell. 

This pull request will be closed, but I noticed that you also changed something for slender structure. Could you please create a new pull request to merge these new changes.

**Comment by Xiangyu-Hu** [comment]
> @rukawaaaaaaa Please look at the new pull request I created. That you proposed is actually another formulation of shell.
> 
> This pull request will be closed, but I noticed that you also changed something for slender structure. Could you please create a new pull request to merge these new changes.

@rukawaaaaaaa @DongWuTUM we may consider to include this formulation in the library too.

**Comment by Xiangyu-Hu** [comment]
the pull request is closed due to another pull request. #413

**Pull request closed without merging**
