### PR TITLE
Fix index error in `ShellContactDensity`

### PR DESCRIPTION
**Pull request by FabienPean-Virtonomy**

### CODE REVIEW

**Review by BenceVirtonomy — APPROVED** [review]

**Comment by Xiangyu-Hu** [comment]
@DongWuTUM Hi, Dong. Could you check whether this bug fix is ok? It failed a case in Mc OS.

**Comment by DongWuTUM** [comment]
> @DongWuTUM Hi, Dong. Could you check whether this bug fix is ok? It failed a case in Mc OS.

OK, I will check it.

**Comment by FabienPean-Virtonomy** [comment]
@DongWuTUM The regression data were generated with the bug present at https://github.com/Xiangyu-Hu/SPHinXsys/commit/ae66a376fc9807033dd63836fbb46bfe35143339

**Comment by Xiangyu-Hu** [comment]
Thanks for the revision.

**Comment by FabienPean-Virtonomy** [comment]
I don't know why macOS is hanging. Tried, several variations, if you have one feel free to fix.

**Comment by DongWuTUM** [comment]
@FabienPean-Virtonomy Hi Fabien. Thank you very much for your revision. Seems like the problem is not located in the regression data. I will further check it.

**Comment by Xiangyu-Hu** [comment]
@ncsalis could you have a look on the branch at mcos?

**Comment by DongWuTUM** [comment]
The simulation sometimes crashed (the time step decreases to very small). This should be the problem.

**Comment by BenceVirtonomy** [comment]
> The simulation sometimes crashed (the time step decreases to very small). This should be the problem. I will correct it.

@DongWuTUM we always check for time step decrease on our side, and stop the simulation if that happens.  It's easier to debug, I would recommend adding it to all simulations in general.

**Comment by DongWuTUM** [comment]
> > The simulation sometimes crashed (the time step decreases to very small). This should be the problem. I will correct it.
> 
> @DongWuTUM we always check for time step decrease on our side, and stop the simulation if that happens. It's easier to debug, I would recommend adding it to all simulations in general.

@BenceVirtonomy Good idea! It should be so.

**Comment by ncsalis** [comment]
> The simulation sometimes crashed (the time step decreases to very small). This should be the problem. I will correct it.

Same thing happens to me. Sometimes crashes with very low dt and sometimes is fine

**Comment by DongWuTUM** [comment]
With adjusted limiter, all are Okay now.

**Pull request merged**
