### PR TITLE
fix warnings from sphinxsys and suppress warnings from tbb and simbody

### PR DESCRIPTION
**Pull request by chuvirtonomy**
1. Resolve all warnings. 
2. Remove warnings from TBB and Simbody
3. Add -Werror to compiler flag
4. Speed up compiling speed

### CODE REVIEW

**Comment by Xiangyu-Hu** [comment]
Still the issue with OSWC case?

**Comment by chuvirtonomy** [comment]
> Still the issue with OSWC case?

Yes. Still not yet figure out why but i will disable it.now.

**Comment by chuvirtonomy** [comment]
I have the same in my local linux:

buntu@ubuntu2004:~/SPHinXsys_main/build/cases_test/test_2d_owsc/bin$ ./test_2d_owsc 
The speed of sound: 115.762
The Lambda: 5.69217e+06
Contact stiffness: 13400.9

 Warning: the variable 'ViscousForceFromFluid' has already registered!
 So, the previously registered variable is assigned!
/home/ubuntu/SPHinXsys_main/SPHINXsys/src/shared/particles/base_particles.h:136
Wave stroke: 0.215151 Wave frequency: 3.14159
terminate called after throwing an instance of 'SimTK::Exception::ErrorCheck'
  what():  SimTK Exception thrown at MassProperties.h:542:
  Error detected by Simbody method Inertia::operator-=(): Diagonals of an Inertia matrix must satisfy the triangle inequality; got 0,0,1.84.
  (Required condition 'Ixx+Iyy+Slop>=Izz && Ixx+Izz+Slop>=Iyy && Iyy+Izz+Slop>=Ixx' was not met.)

Aborted (core dumped)

**Comment by chuvirtonomy** [comment]
@Xiangyu-Hu @BenceVirtonomy  I would like to close this PR. I will create another PR to change test to use source code of simbody 3.7.

**Review by BenceVirtonomy — APPROVED** [review]

**Comment by Xiangyu-Hu** [comment]
Ok.

**Pull request merged**
