### PR TITLE
Uniformize XML serialization for matrix and vector

### PR DESCRIPTION
**Pull request by FabienPean-Virtonomy**

### CODE REVIEW

**Review by RussellSyne — APPROVED** [review]
The tests on both Linux and Windows passed.

**Comment by FabienPean-Virtonomy** [comment]
@Xiangyu-Hu @RussellSyne Is there actually a test checking the reload/restart feature with the XML engine ?

**Comment by Xiangyu-Hu** [comment]
> @Xiangyu-Hu @RussellSyne Is there actually a test checking the reload/restart feature with the XML engine ?

Yes. There are quite some cases using it for particle reload.

**Comment by RussellSyne** [comment]
> @Xiangyu-Hu @RussellSyne Is there actually a test checking the reload/restart feature with the XML engine ?

@FabienPean-Virtonomy I have tested the reload feature with the case "test_2d_fsi2" and the restart feature with the case "test_2d_dambreak" on both Windows and Linux. They all passed.

**Pull request merged**
