### PR TITLE
Non-linear wave - tlp structure interaction

### PR DESCRIPTION
**Pull request by ncsalis**

### CODE REVIEW

**Comment by ncsalis** [comment]
> Hi could could you please expand a bit each example name ? `wfsi` and `nlwfsi` are hard to read and interpret quickly. It would be even better if you could add a small readme in each describing the case and/or a picture

The name wfsi stands for wave floating structure interaction and the nlwfsi stands for non-linear wave fluid structure interaction. I will add the readme and picture example in a future commit, thank you for your suggestion

**Comment by FabienPean-Virtonomy** [comment]
FSI is quite common but the whole acronym made it hard (felt like reading blas/lapack function name 😄),  IMO `wave_fsi` and `nonlinear_wave_fsi` would be clearer

**Comment by ChiZhangatTUM** [comment]
Any experimental data for the validation?

**Comment by ncsalis** [comment]
@FabienPean-Virtonomy Thank you for the suggestion, I will modify the names! 

@ChiZhangatTUM Yes, there are experimental data to validate the model.

**Comment by ncsalis** [comment]
@ChiZhangatTUM sorry, I thought that I already cancelled the checks

**Comment by ChiZhangatTUM** [comment]
The CI bug was fixed and you can merge from master and then PR.

**Comment by Xiangyu-Hu** [comment]
@ncsalis you need pull the master again so that we can merge it to master.

**Comment by ncsalis** [comment]
Before merging with master I have to generate regression ( result changed after using the B correction). 
In this week I will do it

**Review by Xiangyu-Hu — APPROVED** [review]

**Pull request merged**
