### PR TITLE
Fix the bug for level set generation in debug mode

### PR DESCRIPTION
**Pull request by Xiangyu-Hu**
@FengWang3119 @ChenxiZhaoTUM Please have look if this bug fix solve your problem on level set generation.

### CODE REVIEW

**Comment by FengWang3119** [comment]
Still not working for my case.
It is strange, for DL=120 DL=60 it is OK for water_block.defineBodyLevelSetShape(), but for DL=100 it is keeping looping.
QQ_1721067700460
Is is because we use the EXTRUDE?

**Comment by Xiangyu-Hu** [comment]
> Still not working for my case. It is strange, for DL=120 DL=60 it is OK for water_block.defineBodyLevelSetShape(), but for DL=100 it is keeping looping. QQ_1721067700460 Is is because we use the EXTRUDE?

I guess only a close look can find the reason.

**Comment by Xiangyu-Hu** [comment]
Or it is a different issue?

**Comment by Xiangyu-Hu** [comment]
Anyway, I found the previous bug on debug mode solved.

**Review by Lisu-lisa — APPROVED** [review]

**Pull request merged**
