### PR TITLE
Cleaning up solid-multi-resolution

### PR DESCRIPTION
**Pull request by WeiyiVirtonomy**
The branch for solid multi-resolution is merged without cleaning up. 

- [ ] Delete unneeded classes used for test
- [ ] Clean up tests and add gtests

### CODE REVIEW

**Comment by Xiangyu-Hu** [comment]
@WeiyiVirtonomy seems compiling issue.

**Comment by Xiangyu-Hu** [comment]
@WeiyiVirtonomy why delete the 2d case?

**Comment by WeiyiVirtonomy** [comment]
> @WeiyiVirtonomy why delete the 2d case?

I don't have reference data for the 2d example, so I only kept the 3d one. If you think it's better to keep the 2d case, I can add a gtest to compare the single-resolution and multi-resolution result

**Comment by Xiangyu-Hu** [comment]
@WeiyiVirtonomy is the pull request done?

**Comment by WeiyiVirtonomy** [comment]
> @WeiyiVirtonomy is the pull request done?

Yes

**Review by Xiangyu-Hu — APPROVED** [review]

**Pull request merged**
