### PR TITLE
consistency_rkgc

### PR DESCRIPTION
**Pull request by Bo-Zhang1995**
change the correction to RKGC and using the WKGC1 for free surface particles

### CODE REVIEW

**Comment by Bo-Zhang1995** [comment]
The windows test seems have some problem which is still not resolved.

**Comment by Bo-Zhang1995** [comment]
Seems that the windows test is still out of work now.

**Comment by Bo-Zhang1995** [comment]
The Windows test has also passed; could you check and merge it? Thank you. @Xiangyu-Hu

**Comment by Xiangyu-Hu** [comment]
> The Windows test has also passed; could you check and merge it? Thank you. @Xiangyu-Hu

Ok.

**Review by Xiangyu-Hu — APPROVED** [review]

**Pull request merged**
