### PR TITLE
277 switch between double and float

### PR DESCRIPTION
**Pull request by ChiZhangatTUM**
Switch between float and double with the following modification, 
1, DoubleVec -> BiVector
2, TripleVec -> TriVector
3, CaculateDoubleDotProduct -> CaculateBiDotProduct
4, double -> Real
5, SimTK::vecd -> SimTKvecd (Note that when float is using, vector and matrix in float are changed to SimTK vector and float in double to avoid double-build of SimBoby)

With double, tests pass, While the following tests failed due to the large error. 
10:test_2d_dambreak_python
13:test_2d_elastic_gate
16:test_2d_eulerian_taylor_green
30:test_2d_self_contact
31:test_2d_shell
43:test_2d_oscillating_beam_UL
46:test_2d_stfb
47:test_2d_stlw
53:test_vector_functions_particle_relaxation
58:bernoulli_beam_struct_sim
76:test_3d_passive_cantilever
79:test_3d_roof
80:roof_under_self_weight.dp_4
83:test_3d_roof_parametric_cvt
90:test_3d_twisting_column

### CODE REVIEW

**Comment by Xiangyu-Hu** [comment]
Hi @ChiZhangatTUM , there are some conflicts to be solved.

**Comment by ChiZhangatTUM** [comment]
> Hi @ChiZhangatTUM , there are some conflicts to be solved.

Done.

**Comment by Xiangyu-Hu** [comment]
Strange, recently the windows CI can not pass due to the failure on installing gfortran. @FabienPean-Virtonomy .

**Comment by BenceVirtonomy** [comment]
@ChiZhangatTUM @Xiangyu-Hu I would appreciate some discussion on the comments if I take the time to review the PR. If you disagree, just comment why, and that's okay, but ignoring all the comments is not a good practice.

**Comment by ChiZhangatTUM** [comment]
> Strange, recently the windows CI can not pass due to the failure on installing gfortran. @FabienPean-Virtonomy .

This looks like a old bug. I will try to find a solution.

**Comment by Xiangyu-Hu** [comment]
> > Strange, recently the windows CI can not pass due to the failure on installing gfortran. @FabienPean-Virtonomy .
> 
> This looks like a old bug. I will try to find a solution.

CI on linux and mcos both failed.

**Comment by Xiangyu-Hu** [comment]
That means one case runs 6 hours and didn't finish.

**Comment by ChiZhangatTUM** [comment]
> That means one case runs 6 hours and didn't finish.

Understood, I will have a check.

**Comment by ChiZhangatTUM** [comment]
Strange issue is encountered. For example, the test_2d_ball_shell_collision can be executed properly, while Ctest -r takes very long time to run.

**Comment by ChiZhangatTUM** [comment]
@Xiangyu-Hu This PR can be merged.

**Review by Xiangyu-Hu — APPROVED** [review]

**Pull request merged**
