### PR TITLE
2 non-Newtonian industrial application cases & supporting code

### PR DESCRIPTION
**Pull request by TheodorH999**
- **Rushton Turbine Mixer** case with geometry data
- **Twin Screw Extruder** case with geometry data

### CODE REVIEW

**Comment by TheodorH999** [comment]
Mixing Case seems to work. Screw Extruder has penetration now as far as I can test it. I cannot test this well due to the spurious discretization.

**Comment by Xiangyu-Hu** [comment]
> @Xiangyu-Hu Mixing Case seems to work. Screw Extruder has penetration now as far as I can test it. I cannot verify this well due to the spurious discretization.

Ok. We will have look on it.
Xiangyu

**Comment by Xiangyu-Hu** [comment]
@TheodorH999 It seems like compiling using float is failed too.

**Comment by Xiangyu-Hu** [comment]
> @Xiangyu-Hu Mixing Case seems to work. Screw Extruder has penetration now as far as I can test it. I cannot verify this well due to the spurious discretization.

Could you also post the penetration  figure (within the pull request discuss) so that every one can see the problem?

**Comment by TheodorH999** [comment]
> > @Xiangyu-Hu Mixing Case seems to work. Screw Extruder has penetration now as far as I can test it. I cannot verify this well due to the spurious discretization.
> 
> Could you also post the penetration figure (within the pull request discuss) so that every one can see the problem?

**Comment by TheodorH999** [comment]
spurious discretization
I will have to rerun at a smaller resolution, this one is taking to long

**Comment by TheodorH999** [comment]
https://github.com/Xiangyu-Hu/SPHinXsys/assets/119755322/b785dea3-5268-40d1-8885-a615bad6fba4

This is the penetration I observed, it also seems to take place for less coarse resolutions...

**Comment by TheodorH999** [comment]
image
So there is definitely penetration for all resolutions...

**Comment by Xiangyu-Hu** [comment]
Thanks. This is very useful information.

**Comment by Xiangyu-Hu** [comment]
@TheodorH999 It seems that it quite hard to merge this to master now. 
So could you open a branch and merge from your fork to that branch. 
That is sufficient to close this project.

**Review by Xiangyu-Hu — APPROVED** [review]

**Pull request merged**
