### PR TITLE
add nonisotropic kernel documents and cases

### PR DESCRIPTION
**Pull request by Xiaojingtang1234**

### CODE REVIEW

**Comment by Xiaojingtang1234** [comment]
the anisotropic beam  with different anisotropic ratios results
Screenshot from 2023-08-31 13-55-38

the configuration with N_y = 10, anisotropic ratio = 4.0, the red points means the neighbour particles
image

**Comment by Xiangyu-Hu** [comment]
@Xiaojingtang1234 after you clean the code, I will approve it.

**Comment by Xiaojingtang1234** [comment]
I modified the nonisotropic part firstly. and I think it is better to open a new branch for stretching and membrane.

**Comment by Xiangyu-Hu** [comment]
> I modified the nonisotropic part firstly. and I think it is better to open a new branch for stretching and membrane.

Ok.

**Review by Xiangyu-Hu — APPROVED** [review]

**Pull request merged**
