### PR TITLE
add a new Eulerian supersonic flow around a cylinder case

### PR DESCRIPTION
**Pull request by ZhentongWang**
output_velocity_LG
output_pressure_LG

The velocity and pressure contours of the Eulerian supersonic flow around a cylinder using the Laguerre-Gauss kernel are presented.

The main changes are as follows:
1. Two new files, "eulerian_ghost_boundary.h" and "eulerian_ghost_boundary.cpp", are created for adding a new boundary for Eulerian cases, similar with the FVM boundary conditions, based on the zero-order consistency.
2. The classes for creating the ghost particles and the boundary conditions for boundary particles in Eulerian SPH method are introduced. 
3. One class, namely "GhostKernelGradientUpdate", is used for updating the dW_ig and e_ig for the ghost particles to obey the zero-order consistency strictly after implementing the kernel correction.
4. The different approach for calculating the smallest and largest wave speeds in the HLLC Riemann solver is also introduced.

### CODE REVIEW

**Comment by Xiangyu-Hu** [comment]
@ZhentongWang could you also put some figures on the results?

**Comment by ZhentongWang** [comment]
> @ZhentongWang could you also put some figures on the results and brief summary on the changes?

Sure, I have added the pressure and velocity contours of this case, as well as the modification summary.

**Comment by ZhentongWang** [comment]
> > @ZhentongWang could you also put some figures on the results and brief summary on the changes?
> 
> Sure, I have added the pressure and velocity contours of this case, as well as the modification summary.

please see the description comments.

**Comment by Xiangyu-Hu** [comment]
@ZhentongWang also put the updated results?

**Comment by ZhentongWang** [comment]
> @ZhentongWang also put the updated results?

I have updated the velocity and pressure contours.

**Comment by Xiangyu-Hu** [comment]
@ZhentongWang the picture is so small.

**Comment by ZhentongWang** [comment]
> @ZhentongWang the picture is so small.

The contours have been enlarged.

**Review by FengWang3119 — APPROVED** [review]

**Review by FengWang3119 — COMMENTED** [review]
Just curious about the naming, such as rhol_cl, rhor_cr,clr.
And I am confused about the case_name in the regression_test_tool.py,"test_1d_shock_tube"?

**Comment by ZhentongWang** [comment]
> Just curious about the naming, such as rhol_cl, rhor_cr,clr. And I am confused about the case_name in the regression_test_tool.py,"test_1d_shock_tube"?

Thanks for pointing out. l and r means left and right states in the Riemann solver. Here, rhol_cl means rho times sound speed in left state, just like rho0c0_i_ meaning reference rho times reference sound speed of the particle I in the acoustic Riemann solver.

Besides, I have modified the names in the regression file.

**Pull request merged**
