### PR TITLE
Update vcpkg version

### PR DESCRIPTION
**Pull request by FabienPean-Virtonomy**

### CODE REVIEW

**Comment by FabienPean-Virtonomy** [comment]
Updating vcpkg version does not help. It must be an issue linked to an update of the MacOS github runner image. (MacOS versions or included software versions) @Xiangyu-Hu @ChiZhangatTUM

**Comment by FabienPean-Virtonomy** [comment]
@ChiZhangatTUM Updating vcpkg version does not work here. Any more luck on your side?

**Comment by ChiZhangatTUM** [comment]
> @ChiZhangatTUM Updating vcpkg version does not work here. Any more luck on your side?

This is my vcpkg version:
2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba

**Comment by ChiZhangatTUM** [comment]
Seems that macOS-latest is not always  the similar macOS-12 version. I would like to try macOS-13 if the present fails.

**Comment by FabienPean-Virtonomy** [comment]
> This is my vcpkg version:
> 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba

2022 ? It looks like the version of your vcpkg binary app, not the version of the registry of ports you have. Did you `./bootstrap-vcpkg.sh` in your vcpkg folder ?

**Comment by ChiZhangatTUM** [comment]
@FabienPean-Virtonomy Seems that macOS-latest build works, shall we try macOS-13?

**Review by Xiangyu-Hu — APPROVED** [review]

**Pull request merged**
