### PR TITLE
Fix/correction matrix diffusion

### PR DESCRIPTION
**Pull request by Xiangyu-Hu**
Now, the correction matrix for diffusion is an option.
By default, the correction matrix is not applied for contact diffusion.
@ChenxiZhaoTUM please check the changes on regression test.

### CODE REVIEW

**Comment by ChenxiZhaoTUM** [comment]
The case test_2d_advection_diffusion is the same as test_2d_diffusion_RobinBC. I pushed it by mistake, sorry. So the case test_2d_advection_diffusion should be deleted.

**Comment by Xiangyu-Hu** [comment]
@ChenxiZhaoTUM the pull request can only been done after it is approved by you.

**Review by ChenxiZhaoTUM — APPROVED** [review]

**Comment by Xiangyu-Hu** [comment]
@FabienPean-Virtonomy its seems that VCPKG have a problem again for windows system.

**Comment by FabienPean-Virtonomy** [comment]
> @FabienPean-Virtonomy its seems that VCPKG have a problem again for windows system.

@Xiangyu-Hu in what sense, I don't see failed CI ?

**Comment by Xiangyu-Hu** [comment]
Sorry.  It seems passed again.

**Pull request merged**
