### PR TITLE
Try to add the framework for multi-test again 

### PR DESCRIPTION
**Pull request by FengWang3119**
Add the multi-tests framework by using Google Test Fixture, the basic setting is constructed once and several tests can be conducted together.
The code can run on my computer, hope it can pass CI, the testing fixture part is in folder "test_turbulent_module"

### CODE REVIEW

**Comment by Xiangyu-Hu** [comment]
@FengWang3119 I think that the reason for failed CI is because your code is inconsistent with master branch,

**Comment by Xiangyu-Hu** [comment]
@FengWang3119 It seems that you have mixed up several things in one branch which is not typical git based developing practice.

**Comment by FengWang3119** [comment]
I have updated my code to the latest one. I have no idea about the git deloping process, I will try to learn it

**Comment by Xiangyu-Hu** [comment]
@FengWang3119 Many compiling errors in linux CI is due to the strict compiling rule in linux (such as initialization order and unused variables.) CI fails in Windows due to some code
 [3d_sl_static_comfinement_one_phase](https://github.com/FengWang3119/SPHinXsys-FengWang/tree/turbulent-module/tests/user_examples/3d_sl_static_comfinement_one_phase)
which is not able to be compiled.

**Pull request closed without merging**
